---
# tasks file for node
- name: Install NodeJS
  yum: name=nodejs state=present
- name: Create the application directory
  file:
    path: "/var/www/html"
    state: directory

- name: Upload the api directory and package.json file
  copy:   
    src: "/home/shivani/mern-todo"
    dest: "/var/www/html/"

- name: Run npm against package.json
  npm: 
    path: "/var/www/html/mern-todo"

- name: Make server.js executable
  file:
    path: "/var/www/html/mern-todo/server.js"
    mode: 0755

- name: Install NodeJS service
  template:
    src: node.service.j2
    dest: /etc/systemd/system/node.service

- name: Start and enable Node.js
  service: 
    name: node
    state: started
    enabled: yes

- name: Execute a command using the shell module
  command: node /var/www/html/mern-todo/server.js

